# Generated by Django 3.1.4 on 2021-01-26 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=200)),
                ('email', models.EmailField(default=None, max_length=100)),
                ('telefone', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=254)),
                ('cep', models.CharField(max_length=8)),
                ('cpf', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(db_index=True, max_length=200)),
                ('senha', models.CharField(db_index=True, max_length=200)),
                ('FK_pessoa', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='app_pessoa', to='app.pessoa', verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qt_pessoas_casa', models.FloatField(db_index=True)),
                ('data_boleto', models.DateTimeField(db_index=True)),
                ('qt_agua_consumida', models.FloatField(db_index=True)),
                ('total_conta', models.FloatField(db_index=True)),
                ('FK_pessoa', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='app_boleto', to='app.cadastro', verbose_name='Boletos')),
            ],
        ),
    ]
